# Generated by Django 3.0.1 on 2020-01-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='key',
            field=models.CharField(default='sd', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
