# Generated by Django 3.0.1 on 2020-01-07 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_community_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='com_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Community'),
            preserve_default=False,
        ),
    ]
