# Generated by Django 3.0.1 on 2020-01-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='district',
            field=models.CharField(default='as', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='name',
            field=models.CharField(default='as', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='state',
            field=models.CharField(default='as', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='district',
            field=models.CharField(default='asas', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='name',
            field=models.CharField(default='asa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='state',
            field=models.CharField(default='asa', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='tahsil',
            field=models.CharField(max_length=100),
        ),
    ]
