# Generated by Django 3.0.1 on 2020-01-03 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200103_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='key',
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.School'),
            preserve_default=False,
        ),
    ]
