# Generated by Django 3.0.1 on 2020-01-03 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200103_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='school',
            new_name='school_id',
        ),
    ]
