# Generated by Django 3.0.1 on 2020-01-04 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200103_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('School', 'School'), ('Blood Bank', 'Blood Bank'), ('Parent', 'Parent'), ('Hospital', 'Hospital'), ('Teacher', 'Teacher'), ('Community', 'Community'), ('Driver', 'Driver')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_number', models.CharField(max_length=50)),
                ('driving_exp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('age', models.IntegerField()),
                ('photo', models.FileField(upload_to='drivers/')),
                ('mobile_number', models.BigIntegerField()),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('amb_number', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('district', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('mobile_number', models.BigIntegerField()),
                ('state', models.CharField(max_length=50)),
                ('org_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
