# Generated by Django 3.0.1 on 2020-01-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200104_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='amb_number',
            field=models.CharField(max_length=50),
        ),
    ]
