# Generated by Django 3.0.1 on 2020-01-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200104_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='key',
            field=models.CharField(default='asdf', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
