# Generated by Django 3.0.1 on 2020-01-05 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_hospital_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('School', 'School'), ('Blood Bank', 'Blood Bank'), ('Parent', 'Parent'), ('Hospital', 'Hospital'), ('Teacher', 'Teacher'), ('Community', 'Community'), ('Driver', 'Driver'), ('Hospital Staff', 'Hospital Staff')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='HospitalStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('mobile_number', models.BigIntegerField()),
                ('state', models.CharField(max_length=50)),
                ('tahseel', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('staff_type', models.CharField(choices=[('ward', 'ward'), ('lab', 'lab')], max_length=10)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
