# Generated by Django 3.0.1 on 2020-01-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.CharField(choices=[('Scholarship', 'Scholarship'), ('Scheme', 'Scheme'), ('Ed Loan', 'Ed Loan')], max_length=50)),
                ('type', models.CharField(choices=[('State', 'State'), ('Central', 'Central')], max_length=50)),
                ('cat', models.CharField(choices=[('SC/ST', 'SC/ST'), ('OBC', 'OBC'), ('All', 'All'), ('Kashmiri Migrants', 'Kashmiri Migrants')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], max_length=50)),
                ('level', models.CharField(choices=[('Meritorious', 'Meritotrious'), ('All', 'All')], max_length=50)),
                ('beneficiary', models.CharField(max_length=100)),
                ('org', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('desc', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
