# Generated by Django 3.0.1 on 2020-01-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desig', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=50)),
            ],
        ),
    ]
