# Generated by Django 3.0.1 on 2020-01-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('hospital_linked', models.BooleanField()),
                ('service', models.CharField(max_length=50)),
                ('vehicle', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('total', models.IntegerField()),
                ('bGroup', models.CharField(max_length=10)),
                ('amt', models.IntegerField()),
                ('unit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deptt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.BooleanField()),
                ('field2', models.BooleanField()),
                ('field3', models.BooleanField()),
                ('field4', models.BooleanField()),
                ('field5', models.BooleanField()),
                ('type', models.CharField(choices=[('department', 'department'), ('teeka', 'teeka'), ('medicine', 'medicine'), ('ward detail', 'ward detail'), ('ambulance', 'ambulance')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('org', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=50)),
                ('aadhar', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('spec', models.TextField()),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('distric', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HospitalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=50)),
                ('org', models.CharField(max_length=50)),
                ('madicalFacility', models.BooleanField()),
                ('bloodFacility', models.BooleanField()),
            ],
        ),
    ]
