# Generated by Django 3.0.1 on 2019-12-31 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizApp', '0002_auto_20191210_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='', verbose_name='notes/')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApp.Module')),
            ],
        ),
    ]
