# Generated by Django 3.0.1 on 2020-01-07 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0001_initial'),
        ('account', '0003_driver_com_id'),
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.CharField(max_length=20)),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApp.Class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApp.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Teacher')),
            ],
        ),
    ]
