# Generated by Django 3.0.1 on 2019-12-31 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_auto_20191231_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
    ]
