# Generated by Django 3.0.1 on 2020-01-07 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_driver_com_id'),
        ('edu', '0002_teacherdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('notice', models.TextField()),
                ('venue', models.TextField()),
                ('teacher', models.TextField()),
                ('student', models.TextField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.School')),
            ],
        ),
    ]
