# Generated by Django 3.0.1 on 2020-01-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_feedback_studentadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('aadhar', models.BigIntegerField()),
                ('clas', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=30)),
                ('teacher_name', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('validity', models.CharField(max_length=50)),
                ('total_classes', models.IntegerField()),
                ('attended_classes', models.IntegerField()),
                ('exam_name', models.CharField(max_length=50)),
                ('marks', models.IntegerField()),
                ('homework_number', models.IntegerField()),
                ('learning', models.BooleanField()),
                ('behaviour', models.CharField(max_length=50)),
                ('sports', models.CharField(max_length=50)),
                ('extra_act', models.CharField(max_length=50)),
                ('moral_edu', models.CharField(max_length=50)),
                ('concentration', models.CharField(max_length=50)),
                ('suggestions', models.TextField()),
            ],
        ),
    ]
