# Generated by Django 3.0.1 on 2020-01-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_reportcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('select', models.CharField(max_length=50)),
                ('clas', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('video', models.FileField(upload_to='videos/')),
                ('doc', models.FileField(upload_to='docV/')),
            ],
        ),
    ]
