# Generated by Django 3.0.1 on 2020-01-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('clas', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=50)),
                ('probTitle', models.TextField()),
                ('probDesc', models.TextField()),
                ('solTitle', models.TextField()),
                ('solDesc', models.TextField()),
                ('technique', models.TextField()),
                ('doc', models.FileField(upload_to='innovation/')),
            ],
        ),
    ]
